name: CI

on:
  push:
    branches:
      - main

env:
  GIT_USER: aaow
  GIT_EMAIL: chzaaow@gmail.com
  THEME_REPO: fluid-dev/hexo-theme-fluid
  THEME_BRANCH: master
  DEPLOY_REPO: aaow.github.io
  DEPLOY_BRANCH: main

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deployment

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GIT_USER }}/${{ env.DEPLOY_REPO }}
          ref: ${{ DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Git
        run: |
          git config --global user.name ${{ env.GIT_USER }}
          git config --global user.email ${{ env.GIT_EMAIL }}

      - name: Setup SSH Key
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh
          echo "${{ secrets.HEXO_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          npm install --location=global hexo-cli
          npm install
          hexo d